# fly.toml file generated for dovdotdev-redis on 2022-03-10T20:19:10-05:00

app = "dovdotdev-redis"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/redis:6.2.6"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[mounts]]
  destination = "/data"
  source = "redis_server"

[metrics]
  port = 9091
  path = "/metrics"
