# fly.toml file generated for dovdotdev-redis on 2022-04-11T16:24:13-04:00

app = "dovdotdev-redis"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PRIMARY_REGION = "ewr"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/data"
  source = "redis_server"
