[sinks.datadog]
  # General
  type = "datadog_logs" # required
  inputs = ["log_json"] # required
  api_key = "${DATADOG_API_KEY}" # required
  compression = "gzip" # optional, default

  # Encoding
  encoding.codec = "json" # required

  # Healthcheck
  healthcheck.enabled = true # optional, default

