[sinks.uptrace]
  type = "http"
  inputs = ["log_json"]
  encoding.codec = "ndjson"
  compression = "gzip"
  uri = "https://api.uptrace.dev/api/v1/vector-logs"
  headers.uptrace-dsn = "https://${UPTRACE_API_KEY}@api.uptrace.dev/${UPTRACE_PROJECT}"

