app = "dovdotdev-loki"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PRIMARY_REGION = "ewr"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/data"
  source = "loki_storage"
